[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "quick-viz"
version = "0.3.1"
description = "Vizualize CSV quickly"
authors = ["t.ibi", "y.yuji", "y.wada"]
readme = "README.md"
repository = "https://github.com/Taichi-Ibi/quick-viz"

[tool.poetry.dependencies]
python = ">=3.8"
pandas = ">=1.3.0"
pygwalker = "^0.1.4"

[tool.poetry.scripts]
qviz = "qviz.qviz:main"

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
